apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  namespace: notebook
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: darklemon/notebook:latest
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: notebook-work
          mountPath: "/home/meng/work"
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
      volumes:
        - name: notebook-work
          persistentVolumeClaim:
            claimName: notebook-work