apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  namespace: tool
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: darklemon/notebook:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 600
          periodSeconds: 60
        volumeMounts:
        - name: hostvol
          mountPath: "/home/meng/work"
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
      volumes:
        - name: hostvol
          hostPath:
            path: "/home/meng/work"
