apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-work
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 100Gi
  hostPath:
    type: DirectoryOrCreate
    path: /home/meng/work