name: notebook
channels:
  - defaults
  - conda-forge
  - plotly
  - intel
dependencies:
  - python==3.8
  - pip
  - jupyterlab
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - pyarrow
  - matplotlib
  - seaborn
  - dash
  - scikit-learn
  - scikit-learn-intelex
  - imbalanced-learn
  - tqdm
  - sqlalchemy
  - pymysql
  - pymssql
  - networkx
  - neo4j-python-driver
  - pytest
  - cudatoolkit
  - cudnn
  - pip:
    - apache-beam[gcp]
    - google-cloud-bigquery-storage
    - torch
    - torchvision
    - tensorflow-gpu==2.5.0
    - tfx
