apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: tool
spec:
  type: LoadBalancer
  selector:
    app: notebook
  ports:
  - protocol: TCP
    targetPort: 8888
    port: 8888
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.101
