apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
  namespace: {{.Values.namespace.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: cloudbeaver
  ports:
  - protocol: TCP
    port: 8978
    targetPort: 8978
    nodePort: {{.Values.service.nodePort}} 
