apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
  namespace: tool
spec:
  type: NodePort
  selector:
    app: notebook
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30001
