apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: notebook
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888