apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: darklemon/notebook:latest
        imagePullPolicy: IfNotPresent
        name: notebook
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: hostvol
          mountPath: /home/meng/work
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
        - name: hostvol
          hostPath:
            path: /home/meng/Project
