apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-backup
  labels:
    type: local
  namespace: neo4j
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/meng/neo4j/backup"
