apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-backups
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 50Gi
  hostPath:
    type: DirectoryOrCreate
    path: "/home/meng/neo4j/backups"
