apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-backup
  namespace: neo4j
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
