apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-backups
  namespace: neo4j
spec:
  storageClassName: microk8s-hostpath
  volumeName: neo4j-backups
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
