apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: neo4j
  labels:
    run: neo4j
spec:
  type: LoadBalancer
  selector:
    app: neo4j
  ports:
  - name: http
    protocol: TCP
    targetPort: 7474
    port: 7474
  - name: bolt
    protocol: TCP
    targetPort: 7687
    port: 7687
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.103
