apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 20Gi
  hostPath:
    type: DirectoryOrCreate
    path: "/home/enlinea/Airflow"