apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  namespace: airflow
spec:
  storageClassName: microk8s-hostpath
  volumeName: airflow-dags
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
