namespace:
  name: dbeaver
  
image:
  repository: dbeaver/cloudbeaver
  tag: latest
  
replicaCount: 1

volumeMount:
  path: /var/cloudbeaver/workspace
  
service:
  type: NodePort
  nodePort: 30002
