
## Images
images:
  airflow:
    repository: darklemon/airflow
    tag: latest
    pullPolicy: Always

## Webserver secret key
webserverSecretKey: $(python3 -c 'import secrets; print(secrets.token_hex(16))')

## Executor
executor: 'CeleryKubernetesExecutor'
logs:
  persistence:
    enabled: true

## dags
dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags
    
config:
  webserver:
    expose_config: 'True'
    default_wrap: 'True'
  email:
    email_backend: 'airflow.providers.sendgrid.utils.emailer.send_email'
    email_conn_id: 'sendgrid_default'
    from_email: 'noreply@airflow.com'
