apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  accessModes: ["ReadWriteMany"]
  capacity:
    storage: 20Gi
  hostPath:
    type: DirectoryOrCreate
    path: "/home/meng/Work/Airflow/dags"
