apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pv-claim
  namespace: airflow
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
