apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: darklemon/notebook:latest
        ports:
        - name: liveness-port
          containerPort: 8888
        livenessProbe:
          tcpSocket:
            port: liveness-port
          initialDelaySeconds: 600
        volumeMounts:
        - name: hostvol
          mountPath: "/home/meng/work"
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
      volumes:
        - name: hostvol
          hostPath:
            path: "/home/meng/work"
