name: notebook
channels:
  - defaults
  - conda-forge
  - plotly
  - intel
dependencies:
  - python=3.8
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - imbalanced-learn
  - tqdm
  - sqlalchemy
  - pymysql
  - pymssql
  - networkx
  - pytest
  - cudatoolkit
  - cudnn
  - pip
  - pip:
    - tensorflow-gpu
    - torch
    - torchvision
    - torchaudio
    - apache-beam[gcp, interactive]
    - tfx
    - gym