name: notebook
channels:
  - defaults
  - conda-forge
  - plotly
  - intel
dependencies:
  - python==3.8
  - pip
  - jupyterlab
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - imbalanced-learn
  - tqdm
  - sqlalchemy
  - pymysql
  - pymssql
  - networkx
  - pytest
  - cudnn
  - cudatoolkit
  - pip:
    - tensorflow-gpu==2.5.0
    - torch
    - torchvision
    - torchaudio
    - apache-beam[gcp]==2.31.0
    - gym
    - tfx==1.0.0