apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
  namespace: tool
spec:
  type: NodePort
  selector:
    app: notebook
  ports:
    # By default, `targetPort` is set to same value as `port` field.
  - port: 8888
    # Control plane allocate a port from a range (default: 30000-32767)
    nodePort: 30002
