apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: cloudbeaver
  ports:
  - protocol: TCP
    port: 8978
    targetPort: 8978
