apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
      - name: cloudbeaver
        image: dbeaver/cloudbeaver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8978
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8978
        readinessProbe:
          httpGet:
            path: /
            port: 8978
        volumeMounts:
        - name: hostvol
          mountPath: "/opt/cloudbeaver/workspace"
      volumes:
        - name: hostvol
          hostPath:
            path: "/var/cloudbeaver/workspace"
