apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
  namespace: tool
spec:
  type: NodePort
  selector:
    app: cloudbeaver
  ports:
  - protocol: TCP
    port: 8978
    targetPort: 8978
    nodePort: 30002
