apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  labels:
    app: cloudbeaver
  namespace: tool
spec:
  type: NodePort
  selector:
    app: cloudbeaver
  ports:
    # By default, `targetPort` is set to same value as `port` field.
  - port: 8978
    # Control plane allocate a port from a range (default: 30000-32767)
    nodePort: 30001
