apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
      - name: cloudbeaver
        image: dbeaver/cloudbeaver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8978
        livenessProbe:
          tcpSocket:
            port: 8978
          initialDelaySeconds: 600
          periodSeconds: 60
        volumeMounts:
        - name: hostvol
          mountPath: "/opt/cloudbeaver/workspace"
      volumes:
        - name: hostvol
          hostPath:
            path: "/var/cloudbeaver/workspace"
