apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
  labels:
    app: cloudbeaver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
      - name: cloudbeaver
        image: dbeaver/cloudbeaver:latest
        ports:
        - containerPort: 8978
        volumeMounts:
        - name: cloudbeaver-workspace
          mountPath: /opt/cloudbeaver/workspace
      volumes:
        - name: cloudbeaver-workspace
          persistentVolumeClaim:
            claimName: cloudbeaver-workspace