apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudbeaver-workspace
  namespace: cloudbeaver
spec:
  storageClassName: microk8s-hostpath
  volumeName: cloudbeaver-workspace
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi