apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cloudbeaver
  labels:
    run: cloudbeaver
spec:
  type: NodePort
  selector:
    app: cloudbeaver
  ports:
  - port: 8978
    nodePort: 30001