apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cloudbeaver
  labels:
    run: cloudbeaver
spec:
  type: LoadBalancer
  selector:
    app: cloudbeaver
  ports:
  - protocol: TCP
    targetPort: 8978
    port: 8978
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.100